spring.application.name: gateway
server:
    port: 5555
zuul:
  ribbon-isolation-strategy: thread
  host:
    connect-timeout-millis: 600000
    socket-timeout-millis: 600000
  routes:
    api-a:
      path: /sclp/**
      serviceId: FRONT-API
  add-host-header: true
# 确保cookie可以返回给客户端
  sensitive-headers: true

spring.http.multipart.maxFileSize: 10Mb
spring.http.multipart.maxRequestSize: 10Mb
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1122/eureka