spring.application.name: front-api
server:
    port: 8093
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:1122/eureka

slcp:
   upload:
      rootpath: http://slcp.oss-cn-hangzhou.aliyuncs.com/
      oss:
        accesskeyid: LTAI3QEFccJdvdLK
        accesskeysecret: csdyl9RpRqmDKdrA2AYhkr84sv94Lg
        endpoint: oss-cn-hangzhou.aliyuncs.com
        bucket: slcp