spring:
  application:
    name: register

server:
  port: 1122
  enableSelfPreservation: false  
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:1122/eureka/
    register-with-eureka: false